config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: { 
    sessions: 'guests/sessions', 
    registrations: 'guests/registrations'
  }
  devise_for :hosts, controllers: { 
    sessions: 'hosts/sessions',
    registrations: 'hosts/registrations' 
  }
  
  get 'my_bookings', to: 'bookings#my_bookings'
  get 'guesthouse_bookings', to: 'bookings#guesthouse_bookings'
  get 'ongoing_bookings', to: 'bookings#ongoing_bookings'
  get 'host_reviews', to: 'reviews#host_reviews'
  
  root to: 'home#index'

  resources :searches
  resources :guesthouses, except: [:destroy] do
    post 'active', on: :member
    post 'inactive', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'guesthouse_reviews', on: :member
    resources :rooms, except: [:destroy] do
      post 'active', on: :member
      post 'inactive', on: :member
      get 'availability', on: :member
      resources :custom_prices, except: [:destroy]
      resources :bookings, except: [:destroy] do
        get 'host_control', on: :member
        get 'checkout_register', on: :member
        patch 'checkin', on: :member
        patch 'checkout', on: :member
        patch 'host_canceled', on: :member
        patch 'guest_canceled', on: :member
        resources :reviews, only: [:new, :create], shallow: true do
          post 'create_answer', on: :member
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:show, :index] do
        get 'cities', on: :collection
        get 'by_city', on: :collection
        resources :rooms, only: [:index, :show] do
          get 'availability', on: :member
        end
      end
    end
  end
end

app/controllers/api/v1/guesthouses_controller.rb
class Api::V1::GuesthousesController < Api::V1::ApiController

  def index
    guesthouses = Guesthouse.active
    if params[:search].present?
      guesthouses = guesthouses.brand_name_like(params[:search])
    end
    render status: 200, json: guesthouses.order(:brand_name).as_json(only: [:id, :brand_name])
  end

  def show
    guesthouse = Guesthouse.active.find(params[:id])
    
    render status: 200, json: { guesthouse: guesthouse.as_json({except: [:created_at, :updated_at, :registration_number, :corporate_name], methods: :available_rooms })}
  end

  def cities
    cities = Guesthouse.active.pluck(:city).uniq

    render status: 200, json: cities.as_json
  end

  def by_city
    city = params[:city]
    guesthouses_by_city = Guesthouse.active.where(city: city).order(:brand_name)

    render status: 200, json: guesthouses_by_city.order(:city).as_json(except: [:created_at, :updated_at, :registration_number, :corporate_name] )
  end
end

app/controllers/guesthouses_controller.rb
class GuesthousesController < ApplicationController
  before_action :authenticate_host!, except: [:show, :cities, :search, :guesthouse_reviews]
  before_action :set_guesthouse, only: [:show, :edit, :update, :active, :inactive, :guesthouse_reviews]
  before_action :check_host, only: [:edit, :update, :active, :inactive]

  def show 
    @available_rooms = @guesthouse.rooms.where(status: :active)
    @all_rooms = @guesthouse.rooms
    @reviews = @guesthouse.reviews.order(created_at: :desc)
    @newest_reviews = @reviews.first(3)
  end

  def new
    if current_host.guesthouse.present?
      flash[:alert] = t('.error')
      return redirect_to guesthouse_path(current_host.guesthouse)
    end
    @guesthouse = Guesthouse.new
  end
  
  def create
    @guesthouse = current_host.create_guesthouse(guesthouse_params)

    if @guesthouse.save
      flash[:notice] = t('.success', brand_name: @guesthouse.brand_name)
      redirect_to guesthouse_path(@guesthouse)
    else
      flash.now[:alert] = t('.error')
      render :new
    end
  end
      
  def edit
    if @guesthouse.host != current_host
      flash[:alert] = t('.error')
      redirect_to root_path
    end
  end

  def update
    if @guesthouse.update(guesthouse_params)
      flash[:notice] = t('.success', brand_name: @guesthouse.brand_name)
      redirect_to guesthouse_path(@guesthouse.id)
    else
      flash.now[:alert] = t('.error')
      render :new
    end
  end

  def search
    @query_params = params["query"]
    @guesthouses = Guesthouse.search(@query_params)
    if @guesthouses.empty?
      flash.now[:alert] = t('.error')
    end
  end

  def active
    @guesthouse.active!
    flash[:notice] = t('.success')
    redirect_to @guesthouse
  end

  def inactive
    @guesthouse.inactive!
    flash[:alert] = t('.success')
    redirect_to @guesthouse
  end

  def cities
    @city = params[:city]
    @guesthouses = Guesthouse.active.where(city: @city).order(:brand_name)
  end

  def guesthouse_reviews
    @reviews = @guesthouse.reviews.order(created_at: :desc)
    @average_rating = @guesthouse.reviews.pluck(:rating).sum.to_f / @guesthouse.reviews.count
  end

  private

  def set_guesthouse
    @guesthouse = Guesthouse.find(params[:id])
  end

  def guesthouse_params
    params.require(:guesthouse).permit(:description, :brand_name, :corporate_name, :registration_number, :phone_number,
                                      :email, :address, :neighborhood, :city, :state, :postal_code, :payment_method_id, 
                                      :pet_friendly, :usage_policy, :checkin, :checkout, :status)
  end

  def check_host 
    if current_host != @guesthouse.host
      flash[:alert] = t('.error')
      return redirect_to root_path
    end
  end
end

app/views/guesthouses/_form.html.erb
<%= form_with model: guesthouse do |f| %>
  <div>
    <%= f.label :description %>: 
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :brand_name %>: 
    <%= f.text_field :brand_name %>
  </div>

  <div>
    <%= f.label :corporate_name %>: 
    <%= f.text_field :corporate_name %>
  </div>

  <div>
    <%= f.label :registration_number %>: 
    <%= f.text_field :registration_number %>
  </div>

  <div>
    <%= f.label :phone_number %>: 
    <%= f.telephone_field :phone_number %>
  </div>

  <div>
    <%= f.label :email %>: 
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :address %>: 
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :neighborhood %>: 
    <%= f.text_field :neighborhood %>
  </div>

  <div>
    <%= f.label :city %>: 
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :state %>: 
    <%= f.text_field :state %>
  </div>

  <div>
    <%= f.label :postal_code %>: 
    <%= f.text_field :postal_code %>
  </div>

  <div>
    <%= f.label :payment_method_id %>: 
    <%= f.collection_select :payment_method_id, PaymentMethod.all, :id, :method %>
  </div>

  <div>
    <%= f.check_box :pet_friendly %>
    <%= f.label :pet_friendly %>
  </div>

  <div>
    <%= f.label :usage_policy %>: 
    <%= f.text_area:usage_policy %>
  </div>

  <div>
    <%= f.label :checkin %>: 
    <%= f.time_field :checkin %>
  </div>

  <div>
    <%= f.label :checkout %>: 
    <%= f.time_field :checkout %>
  </div>

  <%= f.submit t('helpers.submit.submit') %>

<% end %>

app/views/guesthouses/_guesthouse.html.erb
<div class="container p-2 g-col-8">
<h1> <%= @guesthouse.brand_name %></h1>
<p class="font-monospace"><%= @guesthouse.description %></p>
<div>
    <dl>
      <% if host_signed_in? %> 
        <dt><%= Guesthouse.human_attribute_name(:corporate_name) %>:</dt>
        <dd><%= @guesthouse.corporate_name %></dd>
        <dt><%= Guesthouse.human_attribute_name(:registration_number) %>:</dt>
        <dd><%= @guesthouse.registration_number %></dd>
      <% end %>
      <dt><%= Guesthouse.human_attribute_name(:brand_name) %>:</dt>
      <dd><%= @guesthouse.brand_name %></dd>
      <dt><%= Guesthouse.human_attribute_name(:phone_number) %>:</dt>
      <dd><%= @guesthouse.phone_number %></dd>
      <dt><%= Guesthouse.human_attribute_name(:email) %>:</dt>
      <dd><%= @guesthouse.email %></dd>
      <dt><%= Guesthouse.human_attribute_name(:address) %>:</dt>
      <dd><%= @guesthouse.address %> - <%= @guesthouse.neighborhood %>, <%= @guesthouse.city %> - <%= @guesthouse.state %> - <%= @guesthouse.postal_code %></dd>
      <dt><%= Guesthouse.human_attribute_name(:pet_friendly) %>:</dt>
      <dd><%= @guesthouse.pet_friendly? ? 'Aceita' : 'Não aceita' %></dd>
      <dt><%= Guesthouse.human_attribute_name(:usage_policy) %>:</dt>
      <dd><%= @guesthouse.usage_policy %></dd>
      <dt><%= Guesthouse.human_attribute_name(:payment_method_id) %>:</dt>
      <dd><%= @guesthouse.payment_method.method %></dd>
      <dt><%= Guesthouse.human_attribute_name(:checkin) %>:</dt>
      <dd><%= @guesthouse.checkin.strftime("%H:%M") %></dd>
      <dt><%= Guesthouse.human_attribute_name(:checkout) %>:</dt>
      <dd><%= @guesthouse.checkout.strftime("%H:%M") %></dd>
      <dt><%= Guesthouse.human_attribute_name(:status) %>:</dt>
      <dd><%= I18n.translate(@guesthouse.status) %></dd>
    </dl>
</div>
</div>

app/views/guesthouses/_rooms.html.erb
<div class="container">
  <% if @host && @guesthouse == @host.guesthouse && @all_rooms.any? %>
    <strong><%= t('views.home.rooms') %></strong>
    <div class="list-group">
      <ul>
        <% @all_rooms.each do |room| %>
          <li><%= link_to "#{room.name} - #{room.max_people} pessoas", [@guesthouse, room] %></li>
        <% end %>
      </ul>
    </div>
  <% elsif @available_rooms.any? %>
    <h3><%= t('views.home.rooms') %></h3>
    <ul>
      <% @available_rooms.each do |room| %>
        <li><%= link_to "#{room.name} - #{room.max_people} pessoas", [@guesthouse, room] %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/guesthouses/cities.html.erb
<p> <%= t('views.cities.guesthouses_in') %> <%= @city %></p>

<% @guesthouses.each do |guesthouse| %> 
  <%= link_to "#{guesthouse.brand_name}", guesthouse %></br>
<% end %> 

<%= link_to t('buttons.back'), root_path %>

app/views/guesthouses/edit.html.erb
<h1><%= t('views.edit.manage_guesthouse') %></h1>

<% if @guesthouse.errors.any? %>
  <p><%= t('messages.verify_error') %></p>
  <ul>
    <% @guesthouse.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render partial: 'form', locals: { guesthouse: @guesthouse } %>

app/views/guesthouses/guesthouse_reviews.html.erb
<h4><%= t('views.guesthouse_reviews.reviews_of') %> <%= @guesthouse.brand_name %></h4>
<%= link_to t('helpers.buttons.back'), @guesthouse %>
<div class="d-flex flex-wrap justify-content-around mt-5">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title text-center">
        <%= t('views.guesthouse_reviews.average_rating') %> <%= @average_rating %>
      </h5>

      <% @reviews.each do |review| %>
        <div class="text-center">
          <p><strong><%= review.guest.name %></strong></p>
          <p><sup><%= t('views.guesthouse_reviews.visit_guesthouse') %> <%= review.booking.start_date.strftime('%d/%m/%Y') %></sup></p>
          <p><%= t('views.guesthouse_reviews.rating') %> <%= review.rating %></p>
          <p><%= review.comment %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/guesthouses/new.html.erb
<h1> <%= t('views.home.register_guesthouse') %></h1>

<% if(@guesthouse.errors.any?) %>
  <p><%= t('messages.verify_error') %></p>
  <ul>
    <% @guesthouse.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= render partial: 'form', locals: { guesthouse: @guesthouse } %>

app/views/guesthouses/search.html.erb
<h3><%= t('views.search.result') %> <%= @query_params %></h3>

<p>
  <%= @guesthouses.count %> <%= Guesthouse.model_name.human(count: @guesthouses.count).downcase %> 
  <%= t(:found, count: @guesthouses.count) %>
</p>

<% @guesthouses.each do |guesthouse| %> 
  <ul>
    <li><%= link_to guesthouse.brand_name, guesthouse %></li>
  </ul>
<% end %>

<%= link_to t('helpers.buttons.back'), root_path, class: "btn btn-outline-secondary"  %>

app/views/guesthouses/show.html.erb
<% if current_host.present? && current_host.guesthouse == @guesthouse %>
  <%= link_to t('helpers.buttons.edit'), edit_guesthouse_path, class: "btn btn-outline-primary"  %>
  <% if @guesthouse.inactive? %>
    <%= button_to t('views.home.active_guesthouse'), active_guesthouse_path(@guesthouse.id), class: "btn btn-outline-primary" %>
  <% else %>  
    <%= button_to t('views.home.inactive_guesthouse'), inactive_guesthouse_path(@guesthouse.id), class: "btn btn-outline-danger" %>
  <% end %>
<% end %>

<%= render 'guesthouse' %>
<%= render 'rooms' %>

<div class="container">
  <% if @reviews.any? %>
    <h5><%= t('views.guesthouse_reviews.recent_reviews') %></h5>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title text-center">
          <% @newest_reviews.each do |review| %>
            <p><strong><%= review.guest.name %></strong></p>
            <p><sup> <%= t('views.guesthouse_reviews.visit_guesthouse') %> <%= review.booking.start_date.strftime('%d/%m/%Y') %></sup></p>
            <p>Nota: <%= review.rating %></p>
            <p><%= review.comment %></p>
          <% end %>
        </h5>
      </div>
    </div>
    <%= link_to t('views.guesthouse_reviews.all_reviews'), guesthouse_reviews_guesthouse_path(@guesthouse.id), class: "btn btn-outline-primary" %>
  <% end %>
  <%= link_to t('helpers.buttons.back'), root_path, class: "btn btn-outline-secondary"  %>
</div>