config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: { 
    sessions: 'guests/sessions', 
    registrations: 'guests/registrations'
  }
  devise_for :hosts, controllers: { 
    sessions: 'hosts/sessions',
    registrations: 'hosts/registrations' 
  }
  
  get 'my_bookings', to: 'bookings#my_bookings'
  get 'guesthouse_bookings', to: 'bookings#guesthouse_bookings'
  get 'ongoing_bookings', to: 'bookings#ongoing_bookings'
  get 'host_reviews', to: 'reviews#host_reviews'
  
  root to: 'home#index'

  resources :searches
  resources :guesthouses, except: [:destroy] do
    post 'active', on: :member
    post 'inactive', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'guesthouse_reviews', on: :member
    resources :rooms, except: [:destroy] do
      post 'active', on: :member
      post 'inactive', on: :member
      get 'availability', on: :member
      resources :custom_prices, except: [:destroy]
      resources :bookings, except: [:destroy] do
        get 'host_control', on: :member
        get 'checkout_register', on: :member
        patch 'checkin', on: :member
        patch 'checkout', on: :member
        patch 'host_canceled', on: :member
        patch 'guest_canceled', on: :member
        resources :reviews, only: [:new, :create], shallow: true do
          post 'create_answer', on: :member
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:show, :index] do
        get 'cities', on: :collection
        get 'by_city', on: :collection
        resources :rooms, only: [:index, :show] do
          get 'availability', on: :member
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index
    @guesthouses = Guesthouse.active
      if host_signed_in?
        @guesthouse = current_host.guesthouse 
      end
    @cities = Guesthouse.active.pluck(:city).uniq
    @recent_guesthouses = Guesthouse.active.last(3)
    @other_guesthouses = Guesthouse.active.order(created_at: :desc)[3..] || []
  end
end

app/views/home/_host.html.erb
<div class="d-flex flex-row justify-content-around mt-5">
  <div class="card text-center" style="width: 18rem;">
    <% if @guesthouse.nil? %> 
      <%= link_to t('views.home.register_guesthouse'), new_guesthouse_path, class: "btn btn-outline-primary" %>
        
    <% else %>
    
      <div class="card-header" style="width: 18rem;">
          <% if @guesthouse.inactive? %>
            <%= button_to t('views.home.active_guesthouse'), active_guesthouse_path(@guesthouse.id), class: "btn btn-outline-primary" %>
          <% else %>  
            <%= button_to t('views.home.inactive_guesthouse'), inactive_guesthouse_path(@guesthouse.id), class: "btn btn-outline-danger" %>
          <% end %>
      </div>
          
      <div class="card-body" style="width: 18rem;">
          <h5 class="card-title"> <%= t('views.home.your_guesthouse') %></h5>
          <p class="card-text"><%= current_host.guesthouse.brand_name %></p>
          <p class="card-text"><%= current_host.guesthouse.city %></p>
      </div>
      
      <div class="card-footer text-body-secondary">
          <p><%= link_to t('views.home.see_details'), guesthouse_path(@guesthouse), class: "btn btn-outline-primary" %></p>
          <p><%= link_to t('views.home.add_rooms'), new_guesthouse_room_path(@guesthouse), class: "btn btn-outline-primary" %></p>

          <% if @guesthouse.rooms.any? %>
            <p><%= link_to t('views.home.see_rooms'), guesthouse_rooms_path(@guesthouse), class: "btn btn-outline-primary" %></p>
            <p><%= t('views.home.total_rooms')%> <%= @guesthouse.rooms.count %> </p>
          <% else %> 
            <p> <%= t('views.home.total_rooms') %> 0 </p>
          <% end %>
      </div>
    <% end %>
  </div>
</div>
    

  

app/views/home/index.html.erb
<% if host_signed_in? %>
  <%= render 'host', locals: { guesthouse: @guesthouse } %>
<% end %>

<div class="d-flex flex-row justify-content-around mt-5">
  <form class="d-flex" action="<%= cities_guesthouses_path %>" method="get">
    <select class="form-select me-2" name="city" aria-label="Default select example">
      <option selected><%= t('views.home.search_destination') %></option>
      <% if @cities.present? %>
        <% @cities.each do |city| %>
        <option value="<%= city %>"><%= city %></option>
        <% end %>
      <% end %>
    </select>
    <button type="submit" class="btn btn-primary"><%= t('views.home.search') %></button>
  </form>
</div>

<div class="d-flex flex-row justify-content-around mt-5" >
  <div class="card text-center" style="width: 18rem;">
    <p> <%= t('views.home.recent_guesthouse') %> </p>
    <ul class="list-group list-group-flush">
    <% @recent_guesthouses.each do |guesthouse| %> 
      <li class="list-group-item">
        <%= link_to "#{guesthouse.brand_name} - #{guesthouse.city}", guesthouse %>
      </li>
    <% end %>
    </ul>
  </div>
</div>
  
<div class="d-flex flex-row justify-content-around mt-5" >
  <div class="card text-center" style="width: 18rem;">
    <p> <%= t('views.home.other_guesthouse') %> </p>
    <ul class="list-group list-group-flush">
      <% @other_guesthouses.each do |guesthouse| %> 
        <li class="list-group-item" ></li>
          <%= link_to "#{guesthouse.brand_name} - #{guesthouse.city}", guesthouse %>
        </li>
       <% end %>
    </ul>
  </div>
</div>

<div class="d-flex flex-row justify-content-around mt-5" >
  <div class="card text-center" style="width: 18rem;">
    <% if @guesthouses.empty? %> 
      <p><%= t('views.home.guesthouse_empty') %></p>
    <% end %>
  </div>
</div>