config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: { 
    sessions: 'guests/sessions', 
    registrations: 'guests/registrations'
  }
  devise_for :hosts, controllers: { 
    sessions: 'hosts/sessions',
    registrations: 'hosts/registrations' 
  }
  
  get 'my_bookings', to: 'bookings#my_bookings'
  get 'guesthouse_bookings', to: 'bookings#guesthouse_bookings'
  get 'ongoing_bookings', to: 'bookings#ongoing_bookings'
  get 'host_reviews', to: 'reviews#host_reviews'
  
  root to: 'home#index'

  resources :searches
  resources :guesthouses, except: [:destroy] do
    post 'active', on: :member
    post 'inactive', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'guesthouse_reviews', on: :member
    resources :rooms, except: [:destroy] do
      post 'active', on: :member
      post 'inactive', on: :member
      get 'availability', on: :member
      resources :custom_prices, except: [:destroy]
      resources :bookings, except: [:destroy] do
        get 'host_control', on: :member
        get 'checkout_register', on: :member
        patch 'checkin', on: :member
        patch 'checkout', on: :member
        patch 'host_canceled', on: :member
        patch 'guest_canceled', on: :member
        resources :reviews, only: [:new, :create], shallow: true do
          post 'create_answer', on: :member
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:show, :index] do
        get 'cities', on: :collection
        get 'by_city', on: :collection
        resources :rooms, only: [:index, :show] do
          get 'availability', on: :member
        end
      end
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :guesthouse
  has_many :custom_prices
  has_many :bookings

  validates :description, :name, :size, :max_people, :price, presence: true
  
  enum status: { inactive: 0, active: 1 }


  def has_availability?(start_date, end_date, number_guests)
    start_date_valid?(start_date) && end_date_valid?(start_date, end_date) &&
      dates_available?(start_date, end_date) && has_capacity?(number_guests)  
  end

  def total_price(start_date, end_date)
    total = 0
    (start_date.to_date..end_date.to_date).each do |date|
      next if date == start_date.to_date
      custom_price = find_custom_price(date)
      total += custom_price ? custom_price.price.to_f : price.to_f
    end
    total
  end
  
  private 

  def start_date_valid?(start_date)
    start_date.to_date >= Date.today
  end

  def end_date_valid?(start_date, end_date)
    start_date.to_date < end_date.to_date
  end

  def dates_available?(start_date, end_date)
    new_period = Range.new(start_date.to_date, end_date.to_date)
    bookings.where(status: [:booked, :ongoing]).each do |booking|
      existing_period = Range.new(booking.start_date, booking.end_date)
      return false if new_period.overlaps?(existing_period)
    end
    true
  end

  def has_capacity?(number_guests)
    number_guests.to_i <= max_people.to_i  
  end

  def find_custom_price(date)
    custom_prices.where('? BETWEEN start_date AND end_date', date).first
  end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::ApiController
  
  def availability
    errors = validate_required_params
    if errors.any?
      return render status: 412, json: { errors: errors }
    end

    @room = Room.find(params[:id])
    return render status: 404, json: { error: 'Quarto não encontrado.' } unless @room

    if @room.has_availability?(params[:start_date], params[:end_date], params[:number_guests])
      total_price = @room.total_price(params[:start_date], params[:end_date])
      render status: 200, json: { available: true, total_price: total_price }
    else 
      render status: 200, json: { available: false, message: 'Quarto não disponível para reserva ou número de hóspedes excede a capacidade.' } 
    end
  end

  private

  def validate_required_params
    errors = []
    errors << 'Data de início não pode ficar em branco' unless params[:start_date].present?
    errors << 'Data de término não pode ficar em branco' unless params[:end_date].present?
    errors << 'Número de hóspedes não pode ficar em branco' unless params[:number_guests].present?
    errors
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_host!, except: [:index, :show, :availability]
  before_action :set_guesthouse, except: [:show, :availability]
  before_action :set_room, except: [:new, :create, :index]
  before_action :check_host, only: [:edit, :update]

  def index
    if current_host.present?
      @rooms = @guesthouse.rooms
    else
      @rooms = @guesthouse.rooms.where(status: :active)
    end
  end

  def show
    @guesthouse = Guesthouse.find(params[:guesthouse_id])
    @custom_prices = CustomPrice.all.where(room_id: @room.id)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.guesthouse = @guesthouse

    if @room.save
      flash[:notice] = t('.success', room_name: @room.name)
      redirect_to guesthouse_rooms_path
    else
      flash.now[:alert] = t('.error')
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      flash[:notice] = t('.success', room_name: @room.name)
      redirect_to guesthouse_room_path(guesthouse_id: @guesthouse, id: @room.id)
    else
      flash.now[:alert] = t('.error')
      render :new
    end 
  end

  def active
    @room.active!
    flash[:notice] = t('.success')
    redirect_to guesthouse_room_path(guesthouse_id: @guesthouse, id: @room.id)
  end

  def inactive
    @room.inactive!
    flash[:alert] = t('.success')
    redirect_to guesthouse_room_path(guesthouse_id: @guesthouse, id: @room.id)
  end

  def availability
    @guesthouse = @room.guesthouse

    if params[:start_date].blank? || params[:end_date].blank? || params[:number_guests].blank?
      flash[:alert] = t('.missing')
      return redirect_to guesthouse_room_path(@guesthouse, @room)
    end

    if @room.has_availability?(params[:start_date], params[:end_date], params[:number_guests])
      flash[:notice] = t('.success')
      return redirect_to new_guesthouse_room_booking_path(guesthouse_id: @guesthouse.id , room_id: @room.id, start_date: params[:start_date], end_date: params[:end_date], number_guests: params[:number_guests])
    else 
      flash[:alert] = t('.error')
      return redirect_to guesthouse_room_path(@guesthouse, @room)
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:description, :name, :size, :max_people, :price, :bathroom,
                                :balcony, :air_conditioner, :tv, :wardrobe, :safe, :accessibility, :status)
  end

  def set_guesthouse
    @guesthouse = current_host.guesthouse
  end

  def check_host
    if @room.guesthouse.host != @guesthouse.host
      flash[:alert] = t('.error')
      return redirect_to root_path
    end
  end
end

app/views/rooms/_availability.html.erb
<p><%= t('views.availability.check')%></p>

<%= form_with(url: availability_guesthouse_room_path(@guesthouse, @room), method: :get) do |f| %>
<div>
  <%= f.hidden_field :guesthouse_id, value: guesthouse.id %>
  <%= f.hidden_field :room_id, value: room.id %>
</div>

<div>
  <%= f.label :start_date, t('activerecord.attributes.booking.start_date') %>: 
  <%= f.date_field :start_date, required: true %>
</div>

<div>
  <%= f.label :end_date, t('activerecord.attributes.booking.end_date') %>: 
  <%= f.date_field :end_date, required: true  %>
</div>

<div>
  <%= f.label :number_guests, t('activerecord.attributes.booking.number_guests') %>: 
  <%= f.number_field :number_guests, required: true  %>
</div>

  <%= f.submit t('helpers.buttons.verify') %>
<% end %>

app/views/rooms/_form.html.erb
<% if(@room.errors.any?) %>
  <p><%= t('errors.messages.verify_error') %></p>
  <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: [@guesthouse, @room]) do |f| %>
  <div>
    <%= f.label :name %>: 
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>: 
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :size %>: 
    <%= f.number_field :size %> <%= t('views.form.meter') %>
  </div>

  <div>
    <%= f.label :max_people %>: 
    <%= f.number_field :max_people %> <%= t('views.form.people') %>
  </div>

  <div>
    <%= f.label :price %>: <%= t('views.form.real') %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.check_box :bathroom %>
    <%= f.label :bathroom %>
  </div>

  <div>
    <%= f.check_box :balcony %>
    <%= f.label :balcony %>
  </div>

  <div>
    <%= f.check_box :air_conditioner %>
    <%= f.label :air_conditioner %>
  </div>

  <div>
    <%= f.check_box :tv %>
    <%= f.label :tv %>
  </div>

  <div>
    <%= f.check_box :wardrobe %>
    <%= f.label :wardrobe %>
  </div>

  <div>
    <%= f.check_box :safe %>
    <%= f.label :safe %>
  </div>

  <div>
    <%= f.check_box :accessibility %>
    <%= f.label :accessibility %>
  </div>

  <%= f.submit t('helpers.submit.submit') %>

<% end %>

app/views/rooms/_room.html.erb
<h1><%= t('views.room.room_name', name: @room.name) %></h1>
<p><%= t('views.room.guesthouse_brandname', brand_name: @guesthouse.brand_name) %></p>
<p><%= @room.description %></p>

<div>
  <dl>
    <dt><%= Room.human_attribute_name(:size) %>:</dt>
    <dd><%= @room.size %> <%= t('views.form.meter') %> </dd>
 
    <dt><%= Room.human_attribute_name(:max_people) %>:</dt>
    <dd><%= @room.max_people %> <%= t('views.form.people') %></dd>
    
    <dt><%= Room.human_attribute_name(:price) %>:</dt>
    <dd>R$ <%= @room.price %></dd>
    
    <dt><%= Room.human_attribute_name(:bathroom) %>:</dt>
    <dd><%= @room.bathroom? ? t('views.room.particular') : t('views.room.shared') %></dd>
    
    <dt><%= Room.human_attribute_name(:balcony) %>:</dt>
    <dd><%= @room.balcony? ? t('views.room.it_has') : t('views.room.it_has_not') %></dd>
    
    <dt><%= Room.human_attribute_name(:air_conditioner) %>:</dt>
    <dd><%= @room.air_conditioner? ? t('views.room.it_has') : t('views.room.it_has_not') %></dd>
    
    <dt><%= Room.human_attribute_name(:tv) %>:</dt>
    <dd><%= @room.tv? ? t('views.room.it_has') : t('views.room.it_has_not') %></dd>
    
    <dt><%= Room.human_attribute_name(:wardrobe) %>:</dt>
    <dd><%= @room.wardrobe? ? t('views.room.it_has') : t('views.room.it_has_not') %></dd>
    
    <dt><%= Room.human_attribute_name(:safe) %>:</dt>
    <dd><%= @room.safe? ? t('views.room.it_has') : t('views.room.it_has_not') %></dd>
    
    <dt><%= Room.human_attribute_name(:accessibility) %>:</dt>
    <dd><%= @room.accessibility? ? t('views.room.accessible') : t('views.room.not_accessible') %></dd>
    
    <dt><%= Room.human_attribute_name(:status) %>:</dt>
    <dd><%= I18n.translate(@room.status) %></dd>
  </dl>
</div>

app/views/rooms/edit.html.erb
<h1><%= t('views.edit.manage') %></h1>
<%= render partial: 'form', locals: { room: @room } %>

app/views/rooms/index.html.erb
<ul>
  <% @rooms.each do | room | %>
    <li><%= link_to t('views.index.link_room', name: room.name, max_people: room.max_people), 
        guesthouse_room_path(guesthouse_id: room.guesthouse.id, id: room.id) %></li>
  <% end %> 
</ul>

app/views/rooms/new.html.erb
<h1><%= t('views.new.register') %></h1>
<%= render partial: 'form', locals: { room: @room } %>

app/views/rooms/show.html.erb
<%= render 'room', room: @room %>

<% if host_signed_in? && current_host && @room.guesthouse.host == current_host %>
  <%= link_to t('helpers.buttons.edit'), edit_guesthouse_room_path(@room.id) %>
  <%= link_to t('views.show.add_prices'), new_guesthouse_room_custom_price_path(@room.guesthouse, @room) %>
  
  <% if @custom_prices.any? %>
    <h3><%= t('views.show.special_prices') %></h3>
    <% @custom_prices.each do |custom_price| %>
      <div>
        <strong><%= t('views.show.start') %></strong> <%= custom_price.start_date.strftime("%d/%m/%Y") %>
        <strong><%= t('views.show.end') %></strong> <%= custom_price.end_date.strftime("%d/%m/%Y") %>
        <strong><%= t('views.show.custom_price') %></strong> R$<%= custom_price.price %>
      </div>
    <% end %>
  <% end %>

  <% if @room.inactive? %>
    <%= button_to t('views.show.turn_room_available'), active_guesthouse_room_path(@room.id) %>
  <% else %>
    <%= button_to t('views.show.turn_room_unavailable'), inactive_guesthouse_room_path(@room.id) %>
  <% end %>
<% end %>

<%= render 'availability', room: @room, guesthouse: @guesthouse %>

<div>
  <%= link_to t('helpers.buttons.back'), guesthouse_path %>
</div>