config/routes.rb
Rails.application.routes.draw do
  devise_for :guests, controllers: { 
    sessions: 'guests/sessions', 
    registrations: 'guests/registrations'
  }
  devise_for :hosts, controllers: { 
    sessions: 'hosts/sessions',
    registrations: 'hosts/registrations' 
  }
  
  get 'my_bookings', to: 'bookings#my_bookings'
  get 'guesthouse_bookings', to: 'bookings#guesthouse_bookings'
  get 'ongoing_bookings', to: 'bookings#ongoing_bookings'
  get 'host_reviews', to: 'reviews#host_reviews'
  
  root to: 'home#index'

  resources :searches
  resources :guesthouses, except: [:destroy] do
    post 'active', on: :member
    post 'inactive', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'guesthouse_reviews', on: :member
    resources :rooms, except: [:destroy] do
      post 'active', on: :member
      post 'inactive', on: :member
      get 'availability', on: :member
      resources :custom_prices, except: [:destroy]
      resources :bookings, except: [:destroy] do
        get 'host_control', on: :member
        get 'checkout_register', on: :member
        patch 'checkin', on: :member
        patch 'checkout', on: :member
        patch 'host_canceled', on: :member
        patch 'guest_canceled', on: :member
        resources :reviews, only: [:new, :create], shallow: true do
          post 'create_answer', on: :member
        end
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :guesthouses, only: [:show, :index] do
        get 'cities', on: :collection
        get 'by_city', on: :collection
        resources :rooms, only: [:index, :show] do
          get 'availability', on: :member
        end
      end
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to t('views.home.guesthouse_app'), root_path, class: "navbar-brand" %>

    <div class="navbar-collapse justify-content-start">
      <ul class="navbar-nav">
        <% if host_signed_in? %>
          <li class="nav-link active">
            <%= link_to t('views.home.bookings'), guesthouse_bookings_path, class: "btn btn-outline-primary" %>
          </li>  
          <li class="nav-link active">
            <%= link_to t('views.ongoing_bookings.active_bookings'), ongoing_bookings_path, class: "btn btn-outline-primary" %>
          </li>   
          <li class="nav-link active">
            <%= link_to t('views.home.reviews'), host_reviews_path, class: "btn btn-outline-primary" %>
          </li>      
          <li class="nav-link disabled">
            <%= current_host.description %> 
          </li>
          <li class="nav-item active">
            <%= button_to t('helpers.submit.exit'), destroy_host_session_path, method: :delete, class: "btn btn-outline-secondary" %> 
          </li>
        <% elsif guest_signed_in? %>
          <li class="nav-link active">
            <%= link_to t('views.my_bookings.my'), my_bookings_path, class: "nav-link" %>
          </li> 
          <li class="nav-link disabled">
            <%= current_guest.description %>
          </li>
          <li class="nav-item active">
            <%= button_to t('helpers.submit.exit'), destroy_guest_session_path, method: :delete, class: "btn btn-outline-secondary" %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('helpers.submit.enter_host'), new_host_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('helpers.submit.enter_guest'), new_guest_session_path, class: "nav-link" %>
          </li> 
        <% end %>
      </ul>
    </div>

    <div class="d-flex">
      <%= form_with(url: search_guesthouses_path, method: :get) do |f| %>
        <%= f.text_field :query, placeholder: t('views.home.search_here'), class: "form-control me-2" %>
        <%= f.submit t('views.home.search_guesthouse'), class: "btn btn-outline-primary" %>
      <% end %>
      <small><%= link_to t('views.home.search_detailed'), new_search_path %></small>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('views.home.guesthouse_app') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application" %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <main class="container-fluid">
      <div>
        <% if alert %>
          <div class="alert alert-danger" role="alert"><%= alert %></div>
        <% end %> 
        <% if notice %>
          <div class="alert alert-primary" role="alert"><%= notice %></div>
        <% end %>
      </div>
      
      <%= yield %>
    </main>
  </body>
</html>